//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace goshopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int rowid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string category_name { get; set; }
        public Nullable<int> istop { get; set; }
        public Nullable<int> issale { get; set; }
        public Nullable<int> iscolor { get; set; }
        public Nullable<int> issize { get; set; }
        public string size_name { get; set; }
        public string color_name { get; set; }
        public Nullable<int> browse_count { get; set; }
        public string vendor_no { get; set; }
        public string product_no { get; set; }
        public string product_name { get; set; }
        public string product_spec { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> start_count { get; set; }
        public string remark { get; set; }
        public string product_pre { get; set; }
        public string product_content { get; set; }
        public Nullable<System.DateTime> deadline_end { get; set; }
        public Nullable<System.DateTime> deadline_start { get; set; }
        public string product_tag { get; set; }
        public Nullable<int> ishot { get; set; }
    }
}
